plugins {
    id 'fabric-loom' version '1.1-SNAPSHOT'
    id 'maven-publish'
    id 'idea'
    id "io.freefair.lombok" version "8.0.0-rc3"
}

archivesBaseName = "${mod_name} Fabric ${minecraft_version}"

repositories {
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    // Trinkets
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Ladysnake Libs"
        url = "https://ladysnake.jfrog.io/artifactory/mods"
    }
    //Origins
    maven {
        url 'https://jitpack.io'
    }
    maven {
        name = "AdrianTodt's Maven"
        url = "https://dl.bintray.com/adriantodt/maven"
    }
    maven {
        url "https://maven.jamieswhiteshirt.com/libs-release/"
    }
    maven {
        url "https://maven.shedaniel.me/"
    }
}

dependencies {
    //Fabric and Minecraft
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    //Common
    implementation project(":Common")

    //Auth and Mod Menu
    //modApi "curse.maven:cloth-config-319057:3559638"
    modApi "curse.maven:auth-me-356643:3821981"
    modApi "curse.maven:modmenu-308702:3821162"

    //Libs
    modCompileOnly "dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.1.0"
    modCompileOnly "curse.maven:armorvisibility-387962:3864422"
    modCompileOnly "dev.emi:trinkets:3.6.0"
    modCompileOnly "com.github.apace100:origins-fabric:v1.8.1"

}

loom {
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}


processResources {
    from project(":Common").sourceSets.main.resources
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile) {
    source(project(":Common").sourceSets.main.allSource)
}

jar {
    from("LICENSE") {
        rename { "${it}_${mod_name}" }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
    }
}
