plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id "io.freefair.lombok"
}

base {
    archivesName = "${mod_name} Fabric ${minecraft_version}"
}

repositories {
    maven { url 'https://maven.covers1624.net/' }
}

dependencies {
    // Auth
    localRuntime 'net.covers1624:DevLogin:0.1.0.5'

    //Fabirc and Minecraft
    minecraft "com.mojang:minecraft:${minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    //Mod Menu
    //runtimeOnly "maven.modrinth:modmenu:19.0.0-alpha.1"
}

loom {
    log4jConfigs.from("../log4j-dev.xml")

    runs {
        clientLogin {
            client()
            ideConfigGenerated true
            programArgs '--launch_target', 'net.fabricmc.loader.impl.launch.knot.KnotClient'
            mainClass.set 'net.covers1624.devlogin.DevLogin'
        }
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            programArgs '--username=james090500'
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}
//loom.remapConfigurations.configureEach {
//    configurations.named(it.name) {
//        attributes {
//            attribute(loaderAttribute, 'fabric')
//        }
//    }
//}