plugins {
    id 'java'
    id 'idea'
    id 'maven-publish'
    id 'fabric-loom' version '1.7-SNAPSHOT'
    id "io.freefair.lombok" version "8.4"
}

base {
    archivesName = "${mod_name} Fabric ${minecraft_version}"
}

repositories {
    //Modrinth
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }

    // Trinkets
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name = "Ladysnake Libs"
        url = "https://maven.ladysnake.org/releases"
    }
}

dependencies {
    //Fabric and Minecraft
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    //Common
    compileOnly project(":Common")

    //Auth and Mod Menu
    modLocalRuntime "maven.modrinth:sodium:mc1.20.4-0.5.8"

    modLocalRuntime "maven.modrinth:modmenu:9.0.0"
    modLocalRuntime "maven.modrinth:auth-me:8.0.0+1.20.4"
    modLocalRuntime "maven.modrinth:cloth-config:13.0.121+fabric"

    //TEMP
    modLocalRuntime "maven.modrinth:entity-model-features:2.1.3"
    modLocalRuntime "maven.modrinth:entitytexturefeatures:6.1.3"

    //Libs
    modCompileOnly "dev.onyxstudios.cardinal-components-api:cardinal-components-base:5.4.0"
    //modCompileOnly "maven.modrinth:armor-visibility:20.4.1-fabric"
    modCompileOnly "dev.emi:trinkets:3.8.1"

}

loom {
    if (project(":Common").file("src/main/resources/${mod_id}.accesswidener").exists()) {
        accessWidenerPath.set(project(":Common").file("src/main/resources/${mod_id}.accesswidener"))
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName("Fabric Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Fabric Server")
            ideConfigGenerated(true)
            runDir("run")
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    source(project(":Common").sourceSets.main.allSource)
}
tasks.withType(Javadoc).configureEach {
    source(project(":Common").sourceSets.main.allJava)
}
tasks.named("sourcesJar", Jar) {
    from(project(":Common").sourceSets.main.allSource)
}

processResources {
    from project(":Common").sourceSets.main.resources
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}