plugins {
    id 'io.freefair.lombok' version "8.13.1"
    id 'net.minecraftforge.gradle' version '6.+'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
    id "com.gradleup.shadow" version "9.2.2"
}

// These settings allow you to choose what version of Java you want to be compatible with. Forge 1.7.10 runs on Java 6 to 8.
java.toolchain.languageVersion = JavaLanguageVersion.of(8)
compileJava {
    sourceCompatibility = "8"
    targetCompatibility = "8"
}

base {
    archivesName = "${mod_name} Forge ${minecraft_version}"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")
    config("${mod_id}.mixins.json")
}

minecraft {
    mappings channel: "stable", version: "39-1.12"

    runs {
        client {
            workingDirectory file('run')
            property 'forge.logging.console.level', 'debug'
            args('-torg.spongepowered.asm.launch.MixinTweaker', '--username=james090500')
            jvmArgs '-Dfml.coreMods.load="net.minecraftcapes.mixin.MixinLoader"', '-Dmixin.hotSwap=true', '-Dmixin.checks.interfaces=true'
        }
    }

    legacy {
        fixClasspath = true
    }
}

// This is the configuration for the shadow plugin, which is used to add libraries to the jar.
configurations {
    implementation.extendsFrom(shadowImpl)
}

repositories {
    maven {url = "https://repo.spongepowered.org/maven/" }
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    shadowImpl ("org.spongepowered:mixin:0.8.5-SNAPSHOT") {
        transitive = false
    }

    annotationProcessor 'org.spongepowered:mixin:0.8.5-SNAPSHOT'

    // Required for Dev
    annotationProcessor 'com.google.code.gson:gson:2.8.9'
    annotationProcessor 'com.google.guava:guava:32.1.2-jre'
    annotationProcessor 'org.ow2.asm:asm-debug-all:5.2'
}

jar {
    manifest.attributes (
        "FMLCorePlugin": "net.minecraftcapes.mixin.MixinLoader",
        'FMLCorePluginContainsFMLMod': true,
        'ForceLoadAsMod': true,
        "TweakOrder": 0,
        'TweakClass': 'org.spongepowered.asm.launch.MixinTweaker',
    )
}

processResources {
    // Fill in data
    def expandProps = [
            "version": version,
            "group": project.group, //Else we target the task's group.
            "minecraft_version": minecraft_version,
            "pack_format": pack_format,
            "mod_name": mod_name,
            "mod_author": mod_author,
            "mod_id": mod_id,
            "license": license,
            "description": project.description,
            "forge_version": forge_version,
            "forge_loader_version_range": forge_loader_version_range,
            "credits": credits,
            "java_version": java_version
    ]

    filesMatching(['mcmod.info', 'pack.mcmeta']) {
        expand expandProps
    }

    inputs.properties(expandProps)
}

// This is the configuration for the shadow plugin, which is used to add libraries to the jar.
shadowJar {
    configurations = [project.configurations.shadowImpl]
    duplicatesStrategy = DuplicatesStrategy.WARN
    archiveClassifier.set('')


    mergeServiceFiles {
        include 'META-INF/services/*'
    }
}

tasks.matching { it.name in ["reobfJar"] }.configureEach {
    dependsOn tasks.shadowJar
}

//When Forge 1.12 loads mods from a directory that's been put on the classpath, it expects to find resources in the same directory.
//Default Gradle behavior puts resources in ./build/resources/main instead of ./build/classes/main/java. Let's change that.
sourceSets.configureEach { it.output.resourcesDir = it.output.classesDirs.getFiles().iterator().next() }