buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
        maven { url 'https://repo.spongepowered.org/maven'}
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id "java"
    id "com.github.johnrengelman.shadow" version "2.0.4"
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'

version = "11.2.0"
group = "net.minecraftcapes" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "MinecraftCapes Forge 1.12.2"

sourceCompatibility = targetCompatibility = 1.8 // Java version to compile for.

minecraft {
    mappings channel: 'snapshot', version: '20180814-1.12'

    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            arg '-torg.spongepowered.asm.launch.MixinTweaker'
        }

        server {
            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'
            property 'forge.logging.console.level', 'debug'
            arg '-torg.spongepowered.asm.launch.MixinTweaker'
        }
    }
}

// This is the configuration for the shadow plugin, which is used to add libraries to the jar.
configurations {
    shade
    compile.extendsFrom(shade)
}

assemble.dependsOn shadowJar

// Configures the SpongePowered Repository
repositories {
    maven { url 'https://repo.spongepowered.org/maven/' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'

    shade('org.spongepowered:mixin:0.8.3-SNAPSHOT') {
        exclude module: 'guava'
        exclude module: 'commons-io'
        exclude module: 'gson'
    }

    //Project Lombok
    compile "org.projectlombok:lombok:1.18.12"
}

// Example for how to get properties into the manifest for reading by the runtime..
jar {
    manifest {
        attributes([
                "Specification-Title"        : "minecraftcapes",
                "Specification-Vendor"       : "minecraftcapes",
                "Specification-Version"      : "${version}", // We are version 1 of ourselves
                "Implementation-Title"       : project.name,
                "Implementation-Version"     : "${version}",
                "Implementation-Vendor"      : "minecraftcapes",
                "Implementation-Timestamp"   : new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                "ForceLoadAsMod"             : true,
                "TweakOrder"                 : 0,
                'FMLCorePluginContainsFMLMod': true,
                'TweakClass'                 : 'org.spongepowered.asm.launch.MixinTweaker',
        ])
    }
}

// This is the configuration for the shadow plugin, which is used to add libraries to the jar.
shadowJar {
    configurations = [project.configurations.shade] // Adds the gradle configuration "shade" so we can use it.
    duplicatesStrategy DuplicatesStrategy.EXCLUDE // Prevents duplicates

    classifier ""

    from('build/tmp/compileJava') {
        include 'minecraftcapes.refmap.json' // replace if needed
    }
}

mixin {
    add sourceSets.main, "minecraftcapes.refmap.json"
    config "minecraftcapes.mixins.json"
}

shadowJar.finalizedBy('reobfJar')