plugins {
    id 'idea'
    id 'java'
    id 'io.freefair.lombok' version "${lombok_version}"
    id 'net.minecraftforge.gradle' version '7.+'
    id 'net.minecraftforge.renamer' version '1.1.7'
    id 'com.gradleup.shadow' version '9.6.1'
}

java {
    // Minecraft uses Java 8
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    sourceCompatibility = targetCompatibility = java_version
}

base {
    archivesName = "${mod_name} Forge ${minecraft_version}"
}

// Include generated resources
sourceSets.main.resources.srcDir 'src/generated/resources'

// Libraries that should be bundled into the final mod JAR.
configurations {
    shadowImpl

    implementation.extendsFrom(shadowImpl)
}

repositories {
    minecraft.mavenizer(it)

    maven fg.forgeMaven
    maven fg.minecraftLibsMaven

    mavenCentral()

    maven {
        url = "https://repo.spongepowered.org/maven/"
    }
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")

    shadowImpl("org.spongepowered:mixin:0.7.11-SNAPSHOT") {
        transitive = false
    }
}

minecraft {
    mappings channel: 'stable', version: "12-${minecraft_version}"

    runs {
        configureEach {
            workingDir = layout.projectDirectory.dir('run')
        }

        register('client') {
            args "--username=james090500"

            systemProperty(
                    "fml.coreMods.load",
                    "net.minecraftcapes.mixin.MixinLoader"
            )
        }
    }
}

renamer.enableMixinRefmaps {
    config("${mod_id}.mixins.json")
    refMap = "${mod_id}.refmap.json"
}

renamer.mappings(minecraft.dependency.toSrg)

renamer.classes(tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar)) {
    archiveClassifier = ''

    mappings renamer.mixin.generatedMappings
}

tasks.named('shadowJar', com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    dependsOn tasks.named('jar')

    from(zipTree(tasks.named('jar').get().archiveFile))

    configurations = [project.configurations.shadowImpl]

    archiveClassifier.set('shadow')

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    mergeServiceFiles {
        include 'META-INF/services/*'
    }
}

tasks.named('jar', Jar) {
    archiveClassifier = 'thin'

    from sourceSets.main.output

    manifest.attributes(
            "FMLCorePlugin": "net.minecraftcapes.mixin.MixinLoader",
            "FMLCorePluginContainsFMLMod": true,
            "ForceLoadAsMod": true,
            "TweakOrder": 0,
            "TweakClass": "org.spongepowered.asm.launch.MixinTweaker"
    )
}

tasks.named('processResources') {
    def expandProps = [
            version                    : version,
            group                      : project.group,
            minecraft_version          : minecraft_version,
            pack_format                : pack_format,
            mod_name                   : mod_name,
            mod_author                 : mod_author,
            mod_id                     : mod_id,
            license                    : license,
            description                : project.description,
            forge_version              : forge_version,
            forge_loader_version_range : forge_loader_version_range,
            credits                    : credits,
            java_version               : java_version
    ]

    filesMatching(['mcmod.info', 'pack.mcmeta']) {
        expand expandProps
    }

    inputs.properties(expandProps)
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

afterEvaluate {
    tasks.named('compileJava', JavaCompile) {
        // Mixin 0.7's annotation processor has issues, so use the 0.8.3 processor instead.
        def mixinAp = files("$projectDir/libs/mixin-0.8.3-processor.jar")

        options.annotationProcessorPath =
                (options.annotationProcessorPath ?: configurations.annotationProcessor) + mixinAp
    }
}