# Project
version=12.3.8
group=net.minecraftcapes

# Common
minecraft_version=1.21
mod_id=minecraftcapes
mod_name=MinecraftCapes
mod_author=[james090500,Siriuo]
license=All Rights Reserved
description=Custom Cape, Elytras and Deadmau5 textures for minecraft which everyone with the mod can see!
minecraft_version_range=[1.21]

# Forge
forge_version=51.0.16
forge_loader_version_range=[51,)

# NeoForge
neoforge_version=21.0.21-beta
neoforge_loader_version_range=[4,)

# Fabric
fabric_version=0.100.3+1.21
fabric_loader_version=0.15.11

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false