# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=12.4.0
group=net.minecraftcapes
java_version=21

# Common
minecraft_version=1.21.10-rc1
mod_name=MinecraftCapes
mod_author=[james090500,Siriuo]
mod_id=minecraftcapes
license=All Rights Reserved
credits=
description=Custom Cape, Elytras and Deadmau5 textures for minecraft which everyone with the mod can see!
minecraft_version_range=[1.21.10-rc1]

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.10-rc1-20251002.143406

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.9
parchment_version=2025.10.05

# Common
# https://fabricmc.net/develop/
fabric_loom_version=1.11-SNAPSHOT
# https://projects.neoforged.net/neoforged/moddevgradle
moddev_gradle_version=2.0.112

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.134.1+1.21.10
fabric_loader_version=0.17.2

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.9.15-beta
neoforge_loader_version_range=[4,)

# Forge
forge_version=60.0.0
forge_loader_version_range=[60,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
