# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.0
group=net.minecraftcapes
java_version=17
lombok_version=9.1.0

# Common
minecraft_version=1.20.2
pack_format=18
mod_name=MinecraftCapes
mod_author=[james090500,Siriuo]
mod_id=minecraftcapes
license=All Rights Reserved
credits=
description=Custom Cape, Elytras and Deadmau5 textures for minecraft which everyone with the mod can see!
minecraft_version_range=[1.20.2]

# Common
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.20.2-20241215.201144
# https://projects.neoforged.net/neoforged/moddevgradle
moddev_version=2.0.120

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.91.6+1.20.2
fabric_loader_version=0.18.1
fabric_loom_version=1.13-SNAPSHOT

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=48.1.0
forge_loader_version_range=[48,)

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=20.2.93
neoforge_loader_version_range=[1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false