plugins {
    id 'multiloader-loader'
    id 'io.freefair.lombok'
    id 'net.minecraftforge.gradle' version '[6.0.36,6.2)'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
}

base {
    archivesName = "${mod_name} Forge ${minecraft_version}"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")
    config("${mod_id}.mixins.json")
}

// Automatically enable forge AccessTransformers if the file exists
// This location is hardcoded in FML and can not be changed.
minecraft {
    mappings channel: 'official', version: minecraft_version

    //Calls processResources when in dev
    copyIdeResources = true

    runs {
        configureEach {
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'eventbus.api.strictRuntimeChecks', 'true'
        }
        client {
            main 'net.covers1624.devlogin.DevLogin'
            args '--launch_target', 'net.minecraftforge.bootstrap.ForgeBootstrap'
            property 'forge.enabledGameTestNamespaces', project.mod_id
        }
    }
}

repositories {
    maven { url 'https://maven.covers1624.net/' }
}

jar {
    finalizedBy("reobfJar")
    manifest {
        attributes([
                'MixinConfigs': "${mod_id}.mixins.json",
        ])
    }
}

processResources {
    //Dont use common access transformer
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

sourcesJar {
    //Dont use common access transformer
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    //Dev Login
    runtimeOnly 'net.covers1624:DevLogin:0.1.0.5'

    //Mixins
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
}

// Merge the resources and classes into the same directory.
// This is done because java expects modules to be in a single directory.
// And if we have it in multiple we have to do performance intensive hacks like having the UnionFileSystem
// This will eventually be migrated to ForgeGradle so modders don't need to manually do it. But that is later.
sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}