plugins {
    id 'multiloader-loader'
    id 'io.freefair.lombok' version "8.13.1"
    id 'net.minecraftforge.gradle' version '[6.0.36,6.2)'
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT'
}

base {
    archivesName = "${mod_name} Forge ${minecraft_version}"
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")
    config("${mod_id}.mixins.json")
}

repositories {
    maven { url 'https://maven.covers1624.net/' }
}

minecraft {
    mappings channel: 'official', version: "${minecraft_version}"

    // Tell FG to not automtically create the reobf tasks, as we now use Official mappings at runtime, If you don't use them at dev time then you'll have to fix your reobf yourself.
    reobf = false

    //Calls processResources when in dev
    copyIdeResources = true

    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            args '--username=james090500'
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    //Forge
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    //Dev Login
    runtimeOnly 'net.covers1624:DevLogin:0.1.0.5'

    //Mixins
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
}

// Implement mixinextras properly into the jar.
tasks.named("assemble").configure {
    dependsOn("jarJar")
}

// Implement mixinextras properly into the jar.
tasks.named("jarJar", Jar) {
    archiveClassifier.set("")
}

// Merge the resources and classes into the same directory.
// This is done because java expects modules to be in a single directory.
// And if we have it in multiple we have to do performance intensive hacks like having the UnionFileSystem
// This will eventually be migrated to ForgeGradle so modders don't need to manually do it. But that is later.
sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}