plugins {
    id 'multiloader-loader'
    id 'io.freefair.lombok'
    id 'net.neoforged.gradle.userdev' version '7.1.4'
    id 'net.neoforged.gradle.mixin' version '7.0.0-SNAPSHOT'
}

base {
    archivesName = "${mod_name} NeoForge ${minecraft_version}"
}

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
}

runs {
    configureEach { run ->
        modSource project.sourceSets.main
    }

    client {
        client()
        arguments "--username=james090500"
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }