plugins {
    id 'multiloader-loader'
    id 'io.freefair.lombok'
    id 'net.neoforged.moddev'
}

base {
    archivesName = "${mod_name} NeoForge ${minecraft_version}"
}

neoForge {
    // Specify the version of NeoForge to use.
    version = project.neoforge_version

    runs {
        client {
            client()
            programArgument("--username=james090500")
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }